### ISSUE TITLE
Trouble installing qData

### ISSUE THREAD

**Issue by nlaurens1** [globalgov/qEnviron#10]
I get the following error message when trying to install qData (both with the ```devtools``` and ```remotes``` packages):

![image](https://user-images.githubusercontent.com/56277274/107648593-cd3cf200-6c7c-11eb-9891-751bddde4326.png)

**Comment by henriquesposito** [comment]
@nlaurens1 after updating rTools you were able to install and load qData? Thank you.

**Comment by nlaurens1** [comment]
@henriquesposito Yes, installing the latest version of Rtools and R solved this problem. Thank you!

**Comment by henriquesposito** [comment]
An Q&A discussion has been opened in the GitHub page of qData to account for common issues encountered by users when installing and/or loading qData. Please refer to that forum if any more issues and are found so that they are documented to helper future users. Thank you.
