### ISSUE TITLE
Trouble installing qPackages

### ISSUE THREAD

**Issue by nlaurens1** [globalgov/qEnviron#11]
I receive the following error message when trying to install qPackages:
![image](https://user-images.githubusercontent.com/56277274/107652522-f5c6eb00-6c80-11eb-96e4-9009a8572640.png)

**Comment by henriquesposito** [comment]
Welcome @nlaurens1, 

Please try: `qData::get_packages("globalgov/qEnviron")` and `qData::get_packages("globalgov/qStates")` for loading qPackages. 

Thank you very much for pointing this out. I think we indeed might have an issue with the function as it appears to work only when the organization name is stated and not as users are instructed in the package vignette. 

Running `qData::get_packages()` works on my system though as it lists the q packages available.

Let me know if these fix the issues you are having, or not.

**Comment by nlaurens1** [comment]
Thank you for your help, @henriquesposito. Including "globalgov" in the command does fix the issue concerning individual qPackages.

The issue with the command ```qData::get_packages()``` was apparently caused by another package. I received an error message saying : "cannot remove prior installation of package ‘xfun’" whereas this package wasn't installed in my system. I installed the xfun packages with ```install.packages("xfun")``` and it solved the problem.

**Comment by henriquesposito** [comment]
This issue has been fixed. Please refer to issue #117 on qData for more info. Thank you.
