### ISSUE TITLE
Translate Treaty titles to English

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qEnviron#25]
There are a few treaty titles in other languages that should be translated to English and re-exported to the database, `standardise_titles()` does so if provided with an API key if needed.

**Comment by jhollway** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Global-Governance-Observatory-5f7a2a7a2202cb0023b2a51c/issues/globalgov/qEnviron/25?planning-poker) with ZenHub @EstherPeev @henriquesposito
